# Change these first
owner: eikaramba # Your GitHub organization or username, where this repository lives
repo: notificat-status # The name of this repository

sites:
  - name: Frontpage
    url: https://notific.at
    maxResponseTime: 5000
  - name: API Server
    url: https://notific.at/api/server/health
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.notific.at
  #baseUrl: /notificat-status
  faviconSvg: https://raw.githubusercontent.com/eikaramba/notificat-status/master/assets/notificat.svg
  logoUrl: https://raw.githubusercontent.com/eikaramba/notificat-status/master/assets/notificat.svg
  name: Notific.at Status
  introTitle: "**Uptime Status** for the Notific.at IoT Services."
  introMessage: For more infos see [**Notific.at**](https://notific.at)
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://notific.at

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - eikaramba
